/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity */

#ifndef _Included_com_example_androidex_MainActivity
#define _Included_com_example_androidex_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_MainActivity
 * Method:    moveMotorRight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity_moveMotorRight
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    moveMotorLeft
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity_moveMotorLeft
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    stopMotor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity_stopMotor
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    capture
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_androidex_MainActivity_capture
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
